#!/bin/bash

echo -n "Sisesta oma nimi: "
read nimi

echo -n "Sisesta oma sünniaasta:"
read aasta

praegune_aasta=$(date +%Y)

vanus=$((praegune_aasta - aasta))

echo "Tere tulemast, $nimi!"

echo "$nimi, sina oled $vanus aastat vana."
