#!/bin/bash

echo -n "Sisesta ridade arv: "
read readArv

echo -n "Sisesta tärnide arv reas: "
read tarnideArv

for (( rida=1; rida<=readArv; rida++ ))
do
  echo -n "$rida. "  

  for (( t=1; t<=tarnideArv; t++ ))
  do
    if [ $rida -eq 1 ] || [ $rida -eq $readArv ]; then
      echo -n "* "
    else
      if [ $t -eq 1 ] || [ $t -eq $tarnideArv ]; then
        echo -n "* "
      else
        echo -n "  "
      fi
    fi
  done

  echo ""  
done
