#!/bin/bash

echo -n "Sisesta ridade arv: "
read readArv

for (( rida=1; rida<=readArv; rida++ ))
do
  echo -n "$rida. "  # kuva rea number

  for (( o=1; o<=readArv-rida; o++ ))
  do
    echo -n "o "
  done

  for (( t=1; t<=rida; t++ ))
  do
    echo -n "* "
  done

  echo ""  # reavahetus pärast iga rea lõppu
done
