#!/bin/bash
echo -n "Sisesta suvaline täisarv: "
read arv

positiivne_arv=${arv#-}
summa=0

while [ $positiivne_arv -gt 0 ]
do
  summa=$((summa + positiivne_arv % 10))
  positiivne_arv=$((positiivne_arv / 10))
done

if [ $arv -lt 0 ]
then
  summa=$((-summa))
fi

echo "Arvu $arv numbrite summa on $summa"
