#!/bin/bash

echo -n "Sisesta suvaline arv: "
read arv

if [ $arv -lt 2 ]
then
  echo "$arv - ei ole algarv"
  exit 0
fi

jagaja=2

while [ $jagaja -lt $arv ]
do
  if [ $((arv % jagaja)) -eq 0 ]
  then
    echo "$arv - ei ole algarv"
    exit 0
  fi
  jagaja=$((jagaja + 1))
done

echo "$arv - on algarv"
