#!/bin/bash

#Väljastab kuu numbrile vastava aastaja, mis kasutaja on sisestanud

echo -n "Sisesta kuu number: "
read kuu

if [ $kuu -ge 3 ] && [ $kuu -le 5 ];
then
    echo "Praegu on kevad"
elif [ $kuu -ge 6 ] && [ $kuu -le 8 ];
then
    echo "Praegu on suvi"
elif [ $kuu -ge 9 ] && [ $kuu -le 11 ];
then
    echo "Praegu on sügis"
elif [ $kuu -eq 12 ] || [ $kuu -eq 1 ] || [ $kuu -eq 2 ];
then
    echo "Praegu on talv"
else
    echo "Vale kuu number, sisesta number 1-12"
fi
